title: Release notes for Newspilot Writer and accompanying projects
email: tobias.sodergren@infomaker.se
description: Release notes for Newspilot Writer and accomanying projects
baseurl: "/newspilot-writer-releasenotes" # the subpath of your site, e.g. /blog
url: "https://infomaker.github.io" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-assets

sass:
  sass_dir: _sass

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - build.sh

collections:
  writer-releasenotes:
    output: true
  editorservice-releasenotes:
    output: true
  plugins-releasenotes:
    output: true
