title: Release notes for Digital Writer and accompanying projects
email: tobias.sodergren@infomaker.se
description: Release notes for Digital Writer and accompanying projects
baseurl: "/newspilot-writer-releasenotes" # the subpath of your site, e.g. /blog
url: "https://infomaker.github.io" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-assets

sass:
  sass_dir: _sass

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - build.sh
  - README.md

collections:
  conceptbackend-releasenotes:
    output: true
  editorservice-releasenotes:
    output: true
  imagemetadata-releasenotes:
    output: true
  imagepublish-releasenotes:
    output: true
  imageresizing-releasenotes:
    output: true
  integrationservice-releasenotes:
    output: true
  plugins-releasenotes:
    output: true
  writer-releasenotes:
    output: true
